export const SET_SEARCHED_WORD = "SET_SEARCHED_WORD";
export const GET_ALL_DEVELOPERS = "GET_ALL_DEVELOPERS";
export const ADD_DEVELOPER_STARTED = "ADD_DEVELOPER_STARTED";
export const ADD_DEVELOPER_SUCCESS = "ADD_DEVELOPER_SUCCESS";
export const ADD_DEVELOPER_FAILURE = "ADD_DEVELOPER_FAILURE";
export const GET_DEVELOPER_STARTED = "GET_DEVELOPER_STARTED";
export const GET_DEVELOPER_SUCCESS = "GET_DEVELOPER_SUCCESS";
export const GET_DEVELOPER_FAILURE = "GET_DEVELOPER_FAILURE";
